import { beforeEach, describe, expect, it } from 'vitest';
import { defineElement } from '../../src/core/define';
import {
  VAlert,
  VAvatar,
  VAvatarGroup,
  VBadge,
  VBreadcrumbs,
  VButton,
  VButtonGroup,
  VCheckbox,
  VCheckboxGroup,
  VChip,
  VContainer,
  VDataGrid,
  VDialog,
  VDrawer,
  VEmpty,
  VField,
  VFieldGroup,
  VFileTree,
  VKbd,
  VLink,
  VList,
  VListItem,
  VMenu,
  VMenuItem,
  VGrid,
  VHStack,
  VIcon,
  VIconButton,
  VInput,
  VNav,
  VNavItem,
  VOption,
  VPagination,
  VPanel,
  VPopover,
  VProgress,
  VProperties,
  VProperty,
  VRadio,
  VRadioGroup,
  VScrollArea,
  VSelect,
  VSeparator,
  VShell,
  VSkeleton,
  VSlider,
  VSpinner,
  VSplitPanel,
  VStack,
  VStatusBar,
  VStep,
  VStepper,
  VSwitch,
  VTab,
  VTabPanel,
  VTabs,
  VText,
  VTextarea,
  VToast,
  VToaster,
  VToggle,
  VToggleGroup,
  VToolbar,
  VTooltip,
  VTreeItem,
  VVStack,
  VWindow,
} from '../../src/index';

const registry = [
  ['vui-button', VButton],
  ['vui-button-group', VButtonGroup],
  ['vui-icon-button', VIconButton],
  ['vui-toggle', VToggle],
  ['vui-toggle-group', VToggleGroup],
  ['vui-avatar', VAvatar],
  ['vui-avatar-group', VAvatarGroup],
  ['vui-badge', VBadge],
  ['vui-chip', VChip],
  ['vui-kbd', VKbd],
  ['vui-link', VLink],
  ['vui-separator', VSeparator],
  ['vui-text', VText],
  ['vui-icon', VIcon],
  ['vui-input', VInput],
  ['vui-textarea', VTextarea],
  ['vui-checkbox', VCheckbox],
  ['vui-checkbox-group', VCheckboxGroup],
  ['vui-field', VField],
  ['vui-field-group', VFieldGroup],
  ['vui-radio', VRadio],
  ['vui-radio-group', VRadioGroup],
  ['vui-switch', VSwitch],
  ['vui-select', VSelect],
  ['vui-slider', VSlider],
  ['vui-option', VOption],
  ['vui-dialog', VDialog],
  ['vui-drawer', VDrawer],
  ['vui-menu', VMenu],
  ['vui-menu-item', VMenuItem],
  ['vui-popover', VPopover],
  ['vui-tabs', VTabs],
  ['vui-breadcrumbs', VBreadcrumbs],
  ['vui-pagination', VPagination],
  ['vui-nav', VNav],
  ['vui-nav-item', VNavItem],
  ['vui-stepper', VStepper],
  ['vui-step', VStep],
  ['vui-tab', VTab],
  ['vui-tab-panel', VTabPanel],
  ['vui-tooltip', VTooltip],
  ['vui-alert', VAlert],
  ['vui-empty', VEmpty],
  ['vui-progress', VProgress],
  ['vui-spinner', VSpinner],
  ['vui-skeleton', VSkeleton],
  ['vui-toast', VToast],
  ['vui-toaster', VToaster],
  ['vui-panel', VPanel],
  ['vui-container', VContainer],
  ['vui-scroll-area', VScrollArea],
  ['vui-stack', VStack],
  ['vui-hstack', VHStack],
  ['vui-vstack', VVStack],
  ['vui-grid', VGrid],
  ['vui-split-panel', VSplitPanel],
  ['vui-toolbar', VToolbar],
  ['vui-status-bar', VStatusBar],
  ['vui-shell', VShell],
  ['vui-window', VWindow],
  ['vui-file-tree', VFileTree],
  ['vui-tree-item', VTreeItem],
  ['vui-data-grid', VDataGrid],
  ['vui-list', VList],
  ['vui-list-item', VListItem],
  ['vui-properties', VProperties],
  ['vui-property', VProperty],
] as const;

describe('component naming', () => {
  beforeEach(() => {
    document.body.replaceChildren();
  });

  it('binds each V class to one vui- custom element', () => {
    for (const [name, ctor] of registry) {
      expect(customElements.get(name), name).toBe(ctor);
    }
  });

  it('does not throw when a custom element is registered twice', () => {
    expect(() => defineElement('vui-button', VButton)).not.toThrow();
    expect(() => defineElement('vui-dialog', VDialog)).not.toThrow();
    expect(customElements.get('vui-button')).toBe(VButton);
    expect(customElements.get('vui-dialog')).toBe(VDialog);
  });
});
